packaging_format = 2

id = "synapse-admin-page"
name = "Synapse admin page"
description.en = "Explain in *a few (10~15) words* the purpose of the app or what it actually does (it is meant to give a rough idea to users browsing a catalog of 100+ apps)"
description.fr = "Expliquez en *quelques* (10~15) mots l'utilité de l'app ou ce qu'elle fait (l'objectif est de donner une idée grossière pour des utilisateurs qui naviguent dans un catalogue de 100+ apps)"

version = "1.0~ynh1"

maintainers = ["johndoe"]

[upstream]
license = "MIT"
demo = "https://yaky.dev/apps/synapse-admin/"
code = "https://github.com/yaky-dev/synapse-admin"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/admin"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/yaky-dev/synapse-admin/archive/c121cc6a764bb561ead2f0bea9cae0c49cc2a825.tar.gz"
        sha256 = "af72754b1f9be6b01a0c9119d8295ef374559e4863371ac7999558e2b216c794"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
