packaging_format = 2

id = "synapse-admin-page"
name = "Synapse admin page"
description.en = "Single-page admin tool for Synapse"
description.fr = "single-page admin tool for Synapse"

version = "1.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
demo = "https://yaky.dev/apps/synapse-admin/"
code = "https://github.com/yaky-dev/synapse-admin"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/admin"

    [install.synapse_app]
    ask.en = "Input the Synapse app ID you wish to connect to."
    ask.fr = "Entrez l'ID de l'app Synapse à laquelle vous souhaitez vous connecter."
    help.en = "Leave the default value if you have only one Synapse server installed."
    help.fr = "Laissez la valeur par défaut si vous n'avez installé qu'un seul serveur Synapse."
    type = "string"
    default = "synapse"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/yaky-dev/synapse-admin/archive/c121cc6a764bb561ead2f0bea9cae0c49cc2a825.tar.gz"
        sha256 = "af72754b1f9be6b01a0c9119d8295ef374559e4863371ac7999558e2b216c794"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
